---
- hosts: all
  vars:
    trust_ca_configs:
      - name: test-target-01
        pki_dir: '{{ playbook_dir}}/test-pkis/1'
      - name: test-target-02
        pki_dir: '{{ playbook_dir}}/test-pkis/2'
  roles:
    - role: '{{ playbook_dir}}'
